name: 'Check-Diff-Typo'
description: 'Analyzes and comments on PR diff typos for specified files'
author: 'Rishabh B'
branding:
  icon: 'git-pull-request'
  color: 'green'

inputs:
  files:
    description: 'Comma-separated list of files to analyze'
    required: true
    type: list
  GROQ_API_KEY:
    description: 'Groq API Key'
    required: true
  token:
    description: 'PAT with pull_request:write permission'
    required: true
    default: ${{ github.token }}

outputs:
  comment:
    description: 'Generated comment markdown'
    value: ${{ steps.spelling.outputs.comment }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Setup python env
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Fetch PR base branch
      shell: bash
      run: git fetch origin ${{ github.base_ref }}

    - name: Run typo checker
      id: spelling
      shell: bash
      env:
        PR_BASE: ${{ github.event.pull_request.base.ref }}
        INPUT_FILES: ${{ inputs.files }}
        GROQ_API_KEY: ${{ inputs.GROQ_API_KEY }}
      run: python src/spell_check.py

    - name: Comment PR
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.token }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.spelling.outputs.comment }}
