name: Test Typo Checker
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run script
        id: spelling
        uses: ./
        with:
          token: ${{ secrets.PAT }}
          files: |
            tests/file.txt
            tests/file.json
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
